"""init

Revision ID: a0719f6fe343
Revises:
Create Date: 2025-02-24 14:24:26.932542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a0719f6fe343'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tb_users',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column(
            'name',
            sqlmodel.sql.sqltypes.AutoString(length=150),
            nullable=False,
        ),
        sa.Column(
            'email',
            sqlmodel.sql.sqltypes.AutoString(length=150),
            nullable=False,
        ),
        sa.Column(
            'password', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('current_timestamp(6)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('current_timestamp(6)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_tb_users_email'), 'tb_users', ['email'], unique=True
    )
    op.create_index(op.f('ix_tb_users_id'), 'tb_users', ['id'], unique=True)
    op.create_index(
        op.f('ix_tb_users_name'), 'tb_users', ['name'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_users_name'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_id'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_email'), table_name='tb_users')
    op.drop_table('tb_users')
    # ### end Alembic commands ###
